___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1


#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
print("Версія NumPy:", np.__version__)
print("Конфігурація NumPy:")
np.show_config()

Версія NumPy: 1.23.5
Конфігурація NumPy:
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c

Створити вектор з 10 елементів, заповнений одиницями:

In [3]:
print (np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Створити вектор із значеннями від 0 до 10:

In [4]:
print (np.arange(11))

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [5]:
print (np.zeros((5, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [6]:
v = np.random.randint(0, 10, size = 20)
print (v)
print (np.nonzero(v))

[2 6 0 6 9 4 7 6 0 4 7 0 6 9 2 4 3 7 8 2]
(array([ 0,  1,  3,  4,  5,  6,  7,  9, 10, 12, 13, 14, 15, 16, 17, 18, 19]),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [7]:
print ("Середнє значення:", np.mean(v))
print ("Медіана:", np.median(v))
print ("Стандартне відхилення:", np.std(v))

Середнє значення: 4.6
Медіана: 5.0
Стандартне відхилення: 2.853068523537421


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [8]:
a = np.random.rand(4, 2)
b = np.random.rand(2, 2)

print ("Матриця 1:", a)
print ("Матриця 2:", b)
result = np.dot(a, b)
print ("Результат множення:", result)



Матриця 1: [[0.42737264 0.35528549]
 [0.06237049 0.52118557]
 [0.36130459 0.21770447]
 [0.44440996 0.85761369]]
Матриця 2: [[0.50030424 0.52977099]
 [0.70276824 0.28897111]]
Результат множення: [[0.4634997  0.32907687]
 [0.39747689 0.18364965]
 [0.33375801 0.25431899]
 [0.82504385 0.48326109]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [9]:
res_vec = result.flatten()
print (res_vec)

[0.4634997  0.32907687 0.39747689 0.18364965 0.33375801 0.25431899
 0.82504385 0.48326109]


In [10]:
min_v = np.min(res_vec)
print(min_v )
max_v = np.max(res_vec)
print(max_v)

0.18364965306898579
0.8250438532501392


In [11]:
res_vec[res_vec == max_v] = 0

In [12]:
print (res_vec)

[0.4634997  0.32907687 0.39747689 0.18364965 0.33375801 0.25431899
 0.         0.48326109]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [17]:
corr_mat = np.corrcoef(result[0], result[1:])
print (corr_mat)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Дано матрицю. Знайти ранг матриці:

In [18]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

np.linalg.matrix_rank(a)

3

Знайти визначник матриці:

In [19]:
np.linalg.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [20]:
eigenvalues, eigenvectors = np.linalg.eig(a)
eigenvalues, eigenvectors

(array([14.13520334+0.j        , -4.56760167+3.20389947j,
        -4.56760167-3.20389947j]),
 array([[ 0.43131913+0.j        , -0.31386258-0.47450898j,
         -0.31386258+0.47450898j],
        [ 0.41502436+0.j        , -0.07049527+0.4090732j ,
         -0.07049527-0.4090732j ],
        [ 0.8010734 +0.j        ,  0.7099444 +0.j        ,
          0.7099444 -0.j        ]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [21]:
a = np.random.randint(0,10,50)
counts = np.bincount(a)
most_frequent = np.argmax(counts)
print (a)
print (counts)
print (most_frequent)

[4 5 1 2 3 1 6 7 8 9 4 2 0 5 1 9 9 2 0 2 1 2 3 8 2 2 0 7 6 0 3 7 4 0 3 0 2
 0 3 1 6 2 2 0 2 3 0 0 1 1]
[10  7 11  6  3  2  3  3  2  3]
2


Виведіть лише парні числа, що діляться на 5:

In [22]:
a = np.random.randint(0,10,50)
print (a)

[2 6 7 8 2 9 2 7 9 9 6 8 1 6 1 5 3 3 6 8 0 8 4 5 7 6 7 9 4 8 7 0 9 7 5 5 6
 6 1 8 2 9 0 4 6 0 0 0 5 4]


In [23]:
for i in a:
    if i%5 == 0 and i%2 == 0:
        print (i)

0
0
0
0
0
0


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [24]:
# матриця коефіцієнтів X Y
A = np.array([[2, 5], [1, -10]])

# вектор вільних членів
B = np.array([1, 3])

X = np.linalg.solve(A, B)

print (X)

[ 1.  -0.2]
